name: Trunk Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: Cache Cargo registry
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('Cargo.lock') }}
    - uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: cargo-bin-${{ hashFiles('.github/workflows/trunk.yml') }}
    - uses: cargo-bins/cargo-binstall@main
    - name: Installing WASM toolchain and Trunk
      run: |
        rustup target add wasm32-unknown-unknown
        cargo binstall -y trunk
    - name: Build app
      run: trunk build --release --locked
    - name: List contents
      run: ls -l
    - uses: actions/upload-pages-artifact@v3
      with:
        path: /dist

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
